version: '3.9'

services:
  database:
    image: postgres
    container_name: rentx-database
    # restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - pgdata:/data/postgres

  redis:
    image: redis:alpine
    # restart: always
    container_name: rentx-redis
    ports:
      - ${REDIS_PORT}:6379

  app:
    build: .
    container_name: rentx-api
    # restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
